#!/bin/sh

yinbin=$(./scripts/l yin)
yangexe=$(./scripts/l yang)

echo "[!]              BEGIN!              [!]"
echo "|||                                  |||"

./scripts/x "./${yinbin}" "wine \"${yangexe}\""

hash=$(echo $(./scripts/x "./${yinbin}" "wine \"${yangexe}\"" | tr -d '\0') | md5sum | awk '{ print $1 }')

echo "|+| ${hash} |+|"
echo "[+]               DONE               [+]"
